post http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF1c3RyZWVuYyIsImlkIjoiNjAzYTc3NGRlYjBiODExNzkzM2Y4MDU3IiwiaWF0IjoxNjE0NTM4NzI3fQ.EhY6b52i3xDHcvTKpOnljjBXysl2grX4hTEBN_wTK9w

{
  "title": "Test title",
  "url": "cool.story.bro"
}